server:
  port: 8222

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Authentification
          uri:uri: lb://Authentification
          predicates:
            - Path=/api/**

        - id: WindPFE
          uri: lb://WindPFE # Utilisation de la découverte des services pour le nom de microservice
          predicates:
            - Path=/v2/**
